//
// Created by ida on 10.04.20.
//

#ifndef PRIVATE_INFORMATION_RETRIEVAL_EXIT_CODES_H
#define PRIVATE_INFORMATION_RETRIEVAL_EXIT_CODES_H

#define EXIT_SUCCESS 0
#define EXIT_SERVER_UNREACHABLE 1
#define EXIT_DATA_FILE_NOT_FOUND 2
#define EXIT_DATA_FILE_FORMAT 3
#define EXIT_COULD_NOT_PARSE 4
#define EXIT_UNEXPECTED_CLOSE 5

#endif //PRIVATE_INFORMATION_RETRIEVAL_EXIT_CODES_H
